### ISSUE TITLE
Scale image on different devices.

### ISSUE THREAD

**Issue by tamarahills** [MozScout/scout-ios#30]
The bottom third control should be ~175px.  It's much more on larger devices.

**Comment by tamarahills** [comment]
Image needs to be scaled to fit (screen height - 175px)

**Comment by iukhno** [comment]
@tamarahills we don't support iPads by default. We had only iPhone design. Should we add support of iPads also? It's not very simple to add iPad support  right now. We can put to next phases 2 and 3.

**Comment by dylano** [comment]
@iukhno I don't think iPad is a primary target but it works fine there (I'm testing with one). The main point of this bug is to say the bottom area (with navigation and title) should be a fixed height and then the image should scale to fit whatever remaining space is available. We don't need an iPad-specific layout.

**Comment by iukhno** [comment]
@dylano could you please attache image that illustarte an issue?

**Comment by dylano** [comment]
![image](https://user-images.githubusercontent.com/2423092/41111765-db32171e-6a31-11e8-9a6c-0e16b5496951.png)

**Comment by dylano** [comment]
Related: see issue #39 for additional requirements for the treatment of the image.

**Comment by dylano** [comment]
👍 Verified on build 14.
