### ISSUE TITLE
On Speech rec page change prompt to something in user's queue

### ISSUE THREAD

**Issue by tamarahills** [MozScout/scout-ios#35]
Right now it just says "Say something, I'm listening".  

Want to give them an example of what they can say:
Say "play that article about <search phrase>" where <search phrase> is something from their queue.

**Comment by iukhno** [comment]
We changed "Say something, I'm listening" to "Say "Scout that article about ", because on mobile user stories we had requirement “skim that article about <x>” and “scout that article about <x>“. We don’t have command Play. Do you want to add this word or replace scout?

and one more question - is this just improved label or you would like Scout to say phrase "you can use command play that article about   "

**Comment by iukhno** [comment]
@tamarahills could you please share example of phrase that we should put to this screen
