### ISSUE TITLE
Empty Queue -- Server unavailable case

### ISSUE THREAD

**Issue by tamarahills** [MozScout/scout-ios#37]
When scout can't reach the server, we should have an error message saying:

'Unable to get your articles at this time, please check back later'

If you can include any server error code in the message, that will help

**Comment by dylano** [comment]
For this one, I don't see the "Unable to get..." error message above, just a dialog with an error string "jsonSerialization".

I tested this by taking down the server, but Heroku-hosted apps still serve an error page even if our particular server isn't running, so that's probably why we're getting a JSON error. But still, please include the error string from Tamara above. 


![image](https://user-images.githubusercontent.com/2423092/41169020-7e4e1c2a-6afc-11e8-962a-537770bccc6d.png)

**Comment by Alegero** [comment]
done
